# Created by sim2kid
# Code is on GitHub at https://github.com/sim2kid/waystones

# # # # # # # # # # # # # # # # # # # # # #
#                                         #
#            Simm's Waystones             #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

# In blocks, the max distance you can be to use a waystone.
# When outside this distance, you can't use any waystone commands
# This value must be at least 1
use-distance: 6

# The distance the player has to be to discover a new waystone
# If set to 0 or less, players have to click on the waystone to discover it
discover-distance: 10

# At what distance should effects be played for the nearest waystone?
# You'll want to keep this number above 10ish but below 32ish
near-distance: 20

# The distance to search from the player for lodestones
# The bigger this is, the slower the game will run.
# Try to keep this under 10.
search-radius-lode: 5

# The distance to search from a waystone for a safe tp
# Unlike the lode radius, this only runs on teleports
# You can make this as big as you'd like.
search-radius-tp: 8

# If the waystones should be protected from environmental damage.
no-grief: true




# # # # # # # # # # # # # # # # # # # # # #
#                                         #
#            Waystone Limits              #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

# Waystone Creation Limit Per Player
# Can be bypassed with waystone.create.limit.ignore
# Can also be set in perms with waystone.create.limit.# (Takes highest number)
# Set to -1 to ignore
creation-limit: 8

# Waystone Charge-Up time On Build
# When you place a Waystone, it takes this long before anyone can use it
# The time is measured in seconds
# Can be bypassed with waystone.charge.ignore
# Can also be set in perms with waystone.charge.# (Takes lowest number)
# --> Permission ignored when using diminishing returns.
charge-time: -295

# Charging Math

# Whether to use math to increase charge time with each waystone owned.
# When false, charge-time stays constant
# When true, uses the following values to calculate charge-time
use-diminishing-returns: true

# This is the formula we will use to calculate the charge time:
#                                         [Exponent] + [ExponentLeft]
#  [Actual Charge Time] = [Base] + [Figure]
#
# [Base] = charge-time (listed above)
# [Figure] = charge-figure (down below)
# [Exponent] = Number of Waystones Created (Known in Game)
# [ExponentLeft] = exponent-left
charge-figure: 3.8
# Positive numbers only (And zero)
exponent-left: 4.7
# Set this to true if figure field and exponent fields should be flipped in the formula
flip-figure-and-exponent: true




# # # # # # # # # # # # # # # # # # # # # #
#                                         #
#            Default Values               #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

# True if nametags are enabled by default.
# You can use /waystone nametag <true|false> to toggle it.
default-nametag: true

# The default type of waystone to build.
# Can be [ Public | Private | Discoverable ]
default-access: 'Discoverable'

# The number of waypoints to list using /list
default-list-size: 7





# # # # # # # # # # # # # # # # # # # # # #
#                                         #
#             Random Events               #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

# Teleportation Karma
# If enabled, the more often a player teleports, the more likely a negative event will occur.
teleportation-karma: true
# Number of teleportation per hour a person can handel
karma-limit: 6
# Karma strength
# The strength karma will multiply by to determine other effects
karma-strength: 10.0


# Waystone short circuit
# When enabled, a waystone has a chance of short-circuiting and needing to recharge
waystone-short-circuit: true
# Between 0 and 1, the likelihood of this event happening on teleportation.
# This will increase with karma if enabled
waystone-short-circuit-chance: 0.2
# This will disable the teleportation event on admin stones.
short-circuit-ignore-adminstones: true

# Short Circuit Duration (In Seconds)
# The amount of time it'll take a waystone to recover from a short circuit
# If karma is enabled, the length of a short-circuit will be influenced by a player's TP Karma.
waystone-short-circuit-duration: 30
# This will influence the duration of the event upto the stated amount in both positive and negative directions.
waystone-short-circuit-spread: 15



# Endermites
# When enables, a player has a chance of spawning an endermite on teleportation
spawn-endermites: true
# Between 0 and 1, the likelihood of this event happening on teleportation.
# This will increase with karma if enabled
spawn-endermites-chance: 0.05

# = = = = = = = = = = = = = = = = = = = = #
#           v NOT IMPLEMENTED v           #
# = = = = = = = = = = = = = = = = = = = = #

# Teleportation Sickness
# When enabled, a player may get a variety of negative potion effects after teleporting
# This is best used with karma as the chances will scale when a player has more karma
teleport-sickness: true
teleport-sickness-chance: 0.01



# # # # # # # # # # # # # # # # # # # # # #
#                                         #
#                Redstone                 #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

# Redstone signal of 15 on teleport
# This is equivalent to a redstone block.
redstone-teleport: true

# Redstone signal can deactivate
# When the block receives a redstone signal, teleports will be disabled.
redstone-disable: true

# Comparator output on charging
# Signal strength drops as time decreases.
# 15 signal = 2:00 minutes. 0 signal = 0:00 minutes.
redstone-comparator: true




# # # # # # # # # # # # # # # # # # # # # #
#                                         #
#             Player Actions              #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

# Allow the player to lower the charge time using ender pearls
use-enderpearls: true
# Time lowered by in seconds on use
enderpearl-value: 120

# = = = = = = = = = = = = = = = = = = = = #
#           ^ NOT IMPLEMENTED ^           #
# = = = = = = = = = = = = = = = = = = = = #


# # # # # # # # # # # # # # # # # # # # # #
#                                         #
#              Custom Items               #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

# Use Warp Scrolls.
# Warp Scrolls are one use items that warp to the linked waystone
use-warpscroll: true

# Use Warp Crystals.
# Warp Crystals are multi-use items that warp to a linked waystone
# They will have a small chance of breaking upon use (Which can be affected below)
use-warpcrystal: true

# Soft max on warp crystal uses.
# A crystal is way more likely to break when approaching this many uses
warpcrystal-max-uses: 6
# The max random chance a crystal gets when at 'max-use'
warpcrystal-max-percent: 0.30

# If an item should be consumed even if a teleportation fails.
use-warp-on-fail: false