name: Waystones
version: '${project.version}'
main: com.simmgames.waystones.Waystones
api-version: 1.18
authors: [ sim2kid ]
description: Adds Teleportation via Lodestones in Survival Minecraft
website: https://github.com/sim2kid/waystones
database: false
softdepend: [Vault, NBTApi]
commands:
  waystone:
    description: 'Interact with a Waystone'
    usage: '/waystone'
    permission: 'waystone.command'
    aliases:
      - lodestone
      - waypoint
      - warpstone
  warp:
    description: 'Teleport to another waystone'
    usage: '/warp <[Creator:]<Waystone>> [Creator]'
    permission: 'waystone.command.teleport'
    aliases:
      - teleport
      - way
  webug:
    description: 'debug'
    usage: '/webug'